# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
#Importar numpy
import numpy as np

In [ ]:
#ejercicio 1
# con el comando .zeros(n) realizo un arreglo de ceros de la longitudad deseada
array_ceros = np.zeros(12)
# luego lo imprimo y veo la longitud para corroborar que esté bien
print(array_ceros)
len(array_ceros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [ ]:
#ejercicio 2
# creo el arreglo con el comando .zeros(n) y a la posición 5 le adjudico el
# numero 10
#obs: entiendo al enunciado como 5ta posición que queda como 6to numero
#ya que en python se cuenta el 0
array_ejdos = np.zeros(10)
array_ejdos[5] = 10
print(array_ejdos)


[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [ ]:
#ejercicio 3
array_ejtres = np.arange(10,50)
print(array_ejtres)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#ejercicio 4
array_ejcuatro = np.arange(0,9).reshape(3,3)
print(array_ejcuatro)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#ejercicio 5
array_ejcinco = np.random.rand(100)
print(array_ejcinco)
len(array_ejcinco)
media = np.mean(array_ejcinco)
print(media)
varianza = np.var(array_ejcinco)
print(varianza)

[3.54447975e-01 3.38494807e-01 3.21562253e-01 7.74319927e-01
 1.25764166e-02 5.83989379e-01 8.68815577e-01 2.57822498e-01
 7.07340192e-01 4.75753248e-01 5.92472421e-01 6.20795009e-01
 6.44136416e-02 8.15432255e-01 9.90784406e-01 5.39905323e-01
 7.81002449e-01 2.00741217e-02 4.92697973e-01 4.63953150e-01
 1.99617969e-01 9.43871733e-01 6.04425653e-01 3.84380937e-01
 7.86831462e-01 9.60165942e-01 3.52936789e-01 9.50463900e-01
 1.46549198e-01 1.54378371e-01 8.71453352e-01 8.09953739e-01
 6.53825105e-01 5.52160903e-01 9.35238716e-01 9.66465930e-01
 2.03146779e-01 1.18551696e-02 7.22322283e-01 1.42319067e-01
 4.28782605e-01 2.01390728e-01 8.86196471e-01 1.63573464e-01
 7.65864277e-01 6.36921180e-01 9.05454373e-01 2.68311514e-01
 4.70422568e-01 1.43362267e-01 4.51006351e-01 6.49250733e-01
 3.97850243e-01 3.98193080e-02 5.45283089e-01 5.18880847e-02
 1.83376024e-01 8.15632716e-01 8.61933245e-01 5.01777107e-01
 6.41089103e-01 4.69882127e-01 9.83853115e-01 8.64149833e-02
 1.87677919e-01 4.250522

In [ ]:
#ejercicio 6
mediaejcinco = np.sum(array_ejcinco)/len(array_ejcinco)
print(mediaejcinco)

0.48739793231473194


In [ ]:
#ejercicio 7
varianzaejcinco = np.sum((array_ejcinco - np.mean(array_ejcinco))**2)/len(array_ejcinco)
print(varianzaejcinco)

0.09814504517726991


In [ ]:
#ejercicio 8
array_ejocho = np.random.randn(2)
print(array_ejocho)

[ 0.26585187 -2.37599704]
